In [53]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [54]:
customers = pd.read_csv('../data/raw/customers.csv')

In [55]:
customers.head()

   customer_id  first_name       city    segment signup_date
0            1  Customer_1    Dresden  Corporate  2024-02-01
1            2  Customer_2    Cologne   Consumer  2025-12-17
2            3  Customer_3    Leipzig   Consumer  2024-04-04
3            4  Customer_4  Frankfurt   Consumer  2023-03-02
4            5  Customer_5    Dresden   Consumer  2024-01-04

In [56]:
customers_clean = customers.drop_duplicates()
customers_clean.shape

(5000, 5)

In [57]:
customers_clean[customers_clean.isnull().any(axis=1)]

     customer_id    first_name     city   segment signup_date
117          118  Customer_118      NaN  Consumer  2023-12-31
842          843  Customer_843  Dresden       NaN  2023-03-04

In [58]:
orders = pd.read_csv('../data/raw/orders.csv')
orders.head()

   order_id  customer_id  order_date     status payment_method
0         1         4582  2025-10-16  Completed           Card
1         2         1461  2024-04-08  Completed  Bank Transfer
2         3         3888  2024-08-12  Completed  Bank Transfer
3         4          293  2024-03-15  Completed         PayPal
4         5         1644  2025-12-10  Completed           Card

In [59]:
orders[orders['customer_id'].isin([118, 843])]

       order_id  customer_id  order_date     status payment_method
3139       3140          118  2025-06-21  Completed           Card
10803     10804          118  2025-11-15  Completed           Card
13127     13128          118  2024-11-21  Completed           Card
16558     16559          118  2024-10-04  Completed           Card
17626     17627          118  2025-08-13  Completed         PayPal

In [60]:
customers_clean['city'].value_counts(dropna=False)

city
Berlin        533
Leipzig       516
Hamburg       513
Stuttgart     513
Frankfurt     507
Bremen        496
Cologne       486
Düsseldorf    486
Dresden       479
Munich        470
NaN             1
Name: count, dtype: int64

In [61]:
customers_clean['segment'].value_counts(dropna=False)

segment
Consumer          3218
Corporate         1054
Small Business     727
NaN                  1
Name: count, dtype: int64

In [62]:
products = pd.read_csv('../data/raw/products.csv')
products.head()

   product_id product_name  category  unit_price
0           1  Product_001      Home       35.24
1           2  Product_002     Books       24.59
2           3  Product_003  Clothing       58.74
3           4  Product_004    Sports       28.13
4           5  Product_005    Beauty       22.34

In [63]:
products_clean = products.copy()

In [64]:
products_clean[products_clean.isnull().any(axis=1)]

    product_id product_name category  unit_price
18          19  Product_019      NaN       34.41
54          55  Product_055   Beauty         NaN

In [65]:
order_items = pd.read_csv('../data/raw/order_items.csv')
order_items.head()

   order_item_id  order_id  product_id  quantity  unit_price
0              1     13163          30         1       24.01
1              2      5149          73         1       60.13
2              3     14210          86         3        5.88
3              4     19496          33         2       49.56
4              5     19369          99         1       48.94

In [66]:
order_items[order_items['product_id'].isin([19, 55])]

       order_item_id  order_id  product_id  quantity  unit_price
70                71      5273          55         2         NaN
98                99     14067          55         4         NaN
109              110     15112          55         1         NaN
239              240     10479          19         1       32.73
242              243     12130          55         1         NaN
...              ...       ...         ...       ...         ...
54891          54892     18032          19         1       34.25
54904          54905     16931          19         2       34.01
54935          54936      2065          55         3         NaN
54970          54971     17161          55         2         NaN
54992          54993      4305          55         2         NaN

[1148 rows x 5 columns]

In [67]:
order_items[order_items['unit_price'].isnull()]['product_id'].value_counts()

product_id
55    530
Name: count, dtype: int64

In [68]:
order_items[order_items['product_id'] == 55]['unit_price'].value_counts(dropna=False)

unit_price
NaN    530
Name: count, dtype: int64

In [69]:
order_items['unit_price'].isnull().mean()

np.float64(0.009636188432937584)

In [70]:
order_items.head()

   order_item_id  order_id  product_id  quantity  unit_price
0              1     13163          30         1       24.01
1              2      5149          73         1       60.13
2              3     14210          86         3        5.88
3              4     19496          33         2       49.56
4              5     19369          99         1       48.94

In [71]:
order_items.loc[order_items['unit_price'].isnull(), 'quantity'].sum()

np.int64(892)

In [72]:
products_clean.sort_values('product_id').loc[15:57]

    product_id product_name     category  unit_price
15          16  Product_016       Sports       29.49
16          17  Product_017       Sports       92.42
17          18  Product_018        Books       14.43
18          19  Product_019          NaN       34.41
19          20  Product_020       Beauty       21.06
20          21  Product_021         Home       27.27
21          22  Product_022         Home       26.52
22          23  Product_023         Home       34.70
23          24  Product_024       Beauty       79.48
24          25  Product_025     Clothing      114.01
25          26  Product_026  Electronics       50.74
26          27  Product_027       Beauty       17.52
27          28  Product_028         Home       29.56
28          29  Product_029         Home       39.23
29          30  Product_030         Home       25.42
30          31  Product_031     Clothing       27.66
31          32  Product_032       Sports       31.62
32          33  Product_033  Electronics       54.70
33          34  Product_034       Beauty       46.74
34          35  Product_035         Home       22.27
35          36  Product_036        Books       48.68
36          37  Product_037  Electronics      101.58
37          38  Product_038        Books       12.39
38          39  Product_039  Electronics       24.92
39          40  Product_040         Home       23.72
40          41  Product_041  Electronics       34.88
41          42  Product_042  Electronics       10.12
42          43  Product_043         Home       80.21
43          44  Product_044     Clothing       34.14
44          45  Product_045        Books       40.20
45          46  Product_046     Clothing       37.28
46          47  Product_047        Books       23.67
47          48  Product_048       Sports       52.15
48          49  Product_049        Books       33.23
49          50  Product_050        Books        8.54
50          51  Product_051  Electronics       30.87
51          52  Product_052       Sports       27.65
52          53  Product_053         Home       52.09
53          54  Product_054         Home      191.70
54          55  Product_055       Beauty         NaN
55          56  Product_056       Sports      131.35
56          57  Product_057  Electronics       21.20
57          58  Product_058       Beauty       22.10

In [73]:
order_items[order_items['product_id'] == 19]['unit_price'].value_counts(dropna=False)

unit_price
31.56    6
33.44    5
31.47    5
37.30    5
37.32    4
        ..
37.62    1
33.25    1
36.90    1
34.20    1
34.01    1
Name: count, Length: 410, dtype: int64

In [74]:
order_items[order_items['product_id'] == 19]['order_id'].head()

239    10479
244    19946
253    15651
319    18511
412    16047
Name: order_id, dtype: int64

In [75]:
order_items[order_items['order_id'].isin([239, 10479, 19946, 15651, 18511])]

       order_item_id  order_id  product_id  quantity  unit_price
239              240     10479          19         1       32.73
244              245     19946          19         3       37.27
253              254     15651          19         2       32.02
319              320     18511          19         1       32.02
4280            4281     19946          48         1       51.22
4618            4619     15651          43         1       75.09
5939            5940       239          78         1       18.78
7174            7175       239          99         1       51.87
10609          10610     15651          47         1       24.45
10806          10807     10479          30         1       26.83
13541          13542     15651         100         1       78.91
18689          18690     18511          57         4       20.36
18935          18936     18511          13         1       64.75
18968          18969     18511          28         2       30.05
19135          19136     15651          14         2       23.11
22384          22385     19946          56         4      126.74
24595          24596     19946           8         1       36.74
30050          30051     19946          78         4       19.16
35972          35973     10479          83         1       63.02
43178          43179     10479           7         1       11.12
43603          43604     15651           5         1       22.57
48299          48300     10479          73         1       57.77

In [76]:
order_items[order_items['product_id'] == 55]['unit_price'].value_counts(dropna=False)

unit_price
NaN    530
Name: count, dtype: int64

In [77]:
order_items[order_items['quantity'] <= 0]

      order_item_id  order_id  product_id  quantity  unit_price
3210           3211     19102          72         0       28.91
8888           8889      5131          79        -2       17.82

In [78]:
orders[orders['order_id'].isin([19102, 5131])]

       order_id  customer_id  order_date     status payment_method
5130       5131         4842  2024-02-11  Completed  Bank Transfer
19101     19102         3553  2024-05-19  Completed           Card

In [79]:
order_items[order_items['order_id'] == 5131]

       order_item_id  order_id  product_id  quantity  unit_price
8888            8889      5131          79        -2       17.82
30960          30961      5131          43         1       80.17

In [80]:
order_items[order_items['order_id'] == 19102]

       order_item_id  order_id  product_id  quantity  unit_price
3210            3211     19102          72         0       28.91
8715            8716     19102          80         1       26.66
31968          31969     19102          37         1       99.98

In [81]:
order_items[order_items['order_item_id'].duplicated(keep=False)]

       order_item_id  order_id  product_id  quantity  unit_price
1000            1001     17632           5         4       20.92
55000           1001     17632           5         4       20.92

In [82]:
order_items[~order_items['product_id'].isin(products['product_id'])]

       order_item_id  order_id  product_id  quantity  unit_price
22222          22223      9937        9999         1       63.38

In [83]:
order_items['unit_price'].sort_values(ascending=False).head(10)

12345    9999.99
50285     210.85
33249     210.76
439       210.70
14522     210.57
14977     210.49
21549     210.48
48508     210.46
40050     210.46
53203     210.43
Name: unit_price, dtype: float64

In [86]:
order_items[order_items['unit_price'] == 9999.99]

       order_item_id  order_id  product_id  quantity  unit_price
12345          12346     13858          76         2     9999.99

In [87]:
products[products['product_id'] == 13858]

Empty DataFrame
Columns: [product_id, product_name, category, unit_price]
Index: []

In [89]:
order_items[order_items['product_id'] == 13858]

Empty DataFrame
Columns: [order_item_id, order_id, product_id, quantity, unit_price]
Index: []

In [90]:
order_items.loc[order_items['unit_price'] == 9999.99]

       order_item_id  order_id  product_id  quantity  unit_price
12345          12346     13858          76         2     9999.99

In [91]:
products[products['product_id'] == 76]

    product_id product_name     category  unit_price
75          76  Product_076  Electronics       40.36

In [92]:
orders[orders['order_id'] == 13858]

       order_id  customer_id  order_date     status payment_method
13857     13858         3003  2024-07-25  Cancelled           Card

In [93]:
order_items[order_items['order_id'] == 13858]

       order_item_id  order_id  product_id  quantity  unit_price
9392            9393     13858          62         3       10.53
12345          12346     13858          76         2     9999.99
14391          14392     13858          68         2       44.30
16109          16110     13858          11         4       74.68
18152          18153     13858          12         3       28.02
22038          22039     13858          32         1       33.15
29345          29346     13858          90         1       30.78
36220          36221     13858          43         2       84.40
47593          47594     13858          81         3       37.35
49443          49444     13858          32         3       29.36
50898          50899     13858          74         1       16.32

In [94]:
orders[~orders['customer_id'].isin(customers['customer_id'])]

      order_id  customer_id  order_date    status payment_method
7777      7778        99999  2025-05-31  Returned           Card

In [95]:
orders.isna().sum()

order_id          0
customer_id       0
order_date        0
status            0
payment_method    1
dtype: int64

In [99]:
customers_clean.shape

(5000, 5)

In [100]:
customers_clean = customers_clean.drop_duplicates()

In [101]:
customers_clean.shape

(5000, 5)

In [102]:
customers_clean[customers_clean['city'].isna()]

     customer_id    first_name city   segment signup_date
117          118  Customer_118  NaN  Consumer  2023-12-31

In [103]:
customers_clean[customers_clean['segment'].isna()]

     customer_id    first_name     city segment signup_date
842          843  Customer_843  Dresden     NaN  2023-03-04

In [104]:
products_clean.head()

   product_id product_name  category  unit_price
0           1  Product_001      Home       35.24
1           2  Product_002     Books       24.59
2           3  Product_003  Clothing       58.74
3           4  Product_004    Sports       28.13
4           5  Product_005    Beauty       22.34

In [105]:
products_clean[products_clean['product_id'] == 19]

    product_id product_name category  unit_price
18          19  Product_019      NaN       34.41

In [106]:
products_clean[products_clean['product_id'] == 55]

    product_id product_name category  unit_price
54          55  Product_055   Beauty         NaN

In [107]:
orders_clean = orders.copy()

In [108]:
orders_clean = orders_clean.drop_duplicates()

In [109]:
orders_clean.shape

(20000, 5)

In [110]:
orders_clean.head()

   order_id  customer_id  order_date     status payment_method
0         1         4582  2025-10-16  Completed           Card
1         2         1461  2024-04-08  Completed  Bank Transfer
2         3         3888  2024-08-12  Completed  Bank Transfer
3         4          293  2024-03-15  Completed         PayPal
4         5         1644  2025-12-10  Completed           Card

In [112]:
orders_clean['status'] = orders_clean['status'].str.capitalize()

In [113]:
orders_clean[orders_clean['payment_method'].isna()]

      order_id  customer_id  order_date     status payment_method
1234      1235          239  2024-05-06  Completed            NaN

In [114]:
orders_clean[orders_clean['customer_id'] == 99999]

      order_id  customer_id  order_date    status payment_method
7777      7778        99999  2025-05-31  Returned           Card

In [115]:
order_items_clean = order_items.copy()

In [116]:
order_items_clean = order_items_clean.drop_duplicates()

In [117]:
order_items_clean.shape

(55000, 5)

In [118]:
order_items_clean[order_items_clean['quantity'] <= 0]

      order_item_id  order_id  product_id  quantity  unit_price
3210           3211     19102          72         0       28.91
8888           8889      5131          79        -2       17.82

In [119]:
order_items_clean[~order_items_clean['product_id'].isin(products_clean['product_id'])]

       order_item_id  order_id  product_id  quantity  unit_price
22222          22223      9937        9999         1       63.38

In [120]:
orders_clean['status'].value_counts()

status
Completed    18005
Cancelled     1396
Returned       599
Name: count, dtype: int64

In [123]:
order_items_clean[order_items_clean['quantity'] <= 0].shape

(2, 5)

In [124]:
order_items_clean = order_items_clean[order_items_clean['quantity'] > 0]

In [126]:
order_items_clean.head()

   order_item_id  order_id  product_id  quantity  unit_price
0              1     13163          30         1       24.01
1              2      5149          73         1       60.13
2              3     14210          86         3        5.88
3              4     19496          33         2       49.56
4              5     19369          99         1       48.94

In [127]:
order_items_clean = order_items_clean[order_items_clean['product_id'].isin(products_clean['product_id'])]

In [128]:
order_items_clean = order_items_clean[order_items_clean['unit_price'] != 9999.99]

In [130]:
order_items_clean.shape

(54996, 5)

In [131]:
order_items_clean[order_items_clean['quantity'] <= 0]

Empty DataFrame
Columns: [order_item_id, order_id, product_id, quantity, unit_price]
Index: []

In [134]:
order_items_clean[~order_items_clean['product_id'].isin(products['product_id'])]

Empty DataFrame
Columns: [order_item_id, order_id, product_id, quantity, unit_price]
Index: []

In [135]:
order_items_clean[order_items_clean['unit_price'] == 9999.99]

Empty DataFrame
Columns: [order_item_id, order_id, product_id, quantity, unit_price]
Index: []

In [136]:
orders_clean[~orders_clean['customer_id'].isin(customers_clean['customer_id'])]

      order_id  customer_id  order_date    status payment_method
7777      7778        99999  2025-05-31  Returned           Card

In [137]:
order_items_clean[~order_items_clean['order_id'].isin(orders_clean['order_id'])]

Empty DataFrame
Columns: [order_item_id, order_id, product_id, quantity, unit_price]
Index: []

In [138]:
order_items_clean[
    ~order_items_clean['product_id'].isin(products_clean['product_id'])
]

Empty DataFrame
Columns: [order_item_id, order_id, product_id, quantity, unit_price]
Index: []

In [139]:
customers_clean.to_csv('../data/processed/customers_clean.csv', index=False)
products_clean.to_csv('../data/processed/products_clean.csv', index=False)
orders_clean.to_csv('../data/processed/orders_clean.csv', index=False)
order_items_clean.to_csv('../data/processed/order_items_clean.csv', index=False)